### ISSUE TITLE
[Panic] Panic trying fullcopy

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/syncflux#8]
The following panic was given when trying to do a full copy:

## Config:
````
...
 #
 # data-chuck-duration
 #
 # duration for each small, read  from master -> write to slave, chuck of data
 # smaller chunks of data will use less memory on the syncflux process
 # and also less resources on both master and slave databases
 # greater chunks of data will improve sync speed

 data-chuck-duration = "24h"
...
````

## Command
````
> syncflux -action fullcopy -master masterinfluxdbserver -slave salveinfluxdbserver -start -24h -db db_metrics
````

## Panic:
````
WARN[2019-04-11 12:28:08] Fail to get response from query select * from  "measurement_XXX" where time  > 1554892073s and time < 1554978473s group by *, read database error: unable to decode json: received status code 200 err: net/http: request canceled (Client.Timeout exceeded while reading body)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x818ac1]

goroutine 1 [running]:
github.com/toni-moreno/syncflux/pkg/agent.ReadDB(0xa53120, 0xc0001e6180, 0xc0001ce150, 0xb, 0xc0001ce518, 0x2, 0xc0001ce150, 0xb, 0xc0001ce518, 0x2, ...)
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/agent/client.go:320 +0x231
github.com/toni-moreno/syncflux/pkg/agent.SyncDBRP(0xc0002180a0, 0xc000324000, 0xc0001ce150, 0xb, 0xc0001cce40, 0xbf238ba641241262, 0xffffae253e9b1422, 0xdfe720, 0xbf23e38a40ede6de, 0x6c8099, ...)
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/agent/client.go:528 +0x65d
github.com/toni-moreno/syncflux/pkg/agent.(*HACluster).ReplicateData(0xc0001df110, 0xc0001c63b8, 0x1, 0x1, 0xbf238ba641241262, 0xffffae253e9b1422, 0xdfe720, 0xbf23e38a40ede6de, 0x6c8099, 0xdfe720, ...)
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/agent/hacluster.go:162 +0x1ee
github.com/toni-moreno/syncflux/pkg/agent.SchCopy(0x7ffd1088a7c9, 0xa, 0x7ffd1088a7db, 0xa, 0x7ffd1088a7f6, 0xb, 0xbf238ba641241262, 0xffffae253e9b1422, 0xdfe720, 0xbf23e38a40ede6de, ...)
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/agent/agent.go:172 +0x21d
main.main()
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/main.go:250 +0x488
````

**Comment by toni-moreno** [comment]
Closed as is the same case that #1
